// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG50P_bwodtr6MA7nF-pK12dTzCxSJIsg',
    appId: '1:110028724792:web:5333d090be208444e3a4cd',
    messagingSenderId: '110028724792',
    projectId: 'flutter-note-fb92b',
    authDomain: 'flutter-note-fb92b.firebaseapp.com',
    storageBucket: 'flutter-note-fb92b.firebasestorage.app',
    measurementId: 'G-MK50TTP75B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZmY7cwPeJrcsMM81Gmx5DB6aMrJnoX1c',
    appId: '1:110028724792:android:aaefb8a9efbadbb1e3a4cd',
    messagingSenderId: '110028724792',
    projectId: 'flutter-note-fb92b',
    storageBucket: 'flutter-note-fb92b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7WXG_O1DIlqmTzwtwrn5xukSrcdKZKPs',
    appId: '1:110028724792:ios:954ade46f78ae436e3a4cd',
    messagingSenderId: '110028724792',
    projectId: 'flutter-note-fb92b',
    storageBucket: 'flutter-note-fb92b.firebasestorage.app',
    iosBundleId: 'com.example.flutterNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7WXG_O1DIlqmTzwtwrn5xukSrcdKZKPs',
    appId: '1:110028724792:ios:954ade46f78ae436e3a4cd',
    messagingSenderId: '110028724792',
    projectId: 'flutter-note-fb92b',
    storageBucket: 'flutter-note-fb92b.firebasestorage.app',
    iosBundleId: 'com.example.flutterNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG50P_bwodtr6MA7nF-pK12dTzCxSJIsg',
    appId: '1:110028724792:web:a3123ae3758b5b7ee3a4cd',
    messagingSenderId: '110028724792',
    projectId: 'flutter-note-fb92b',
    authDomain: 'flutter-note-fb92b.firebaseapp.com',
    storageBucket: 'flutter-note-fb92b.firebasestorage.app',
    measurementId: 'G-B4LX4BYF85',
  );

}